//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrucibleData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fisheye.inside.nokiasiemensnetworks.com/rest-service/auth-v1/login?userNa" +
            "me={0}&password={1}")]
        public string LoginUrl {
            get {
                return ((string)(this["LoginUrl"]));
            }
            set {
                this["LoginUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fisheye.inside.nokiasiemensnetworks.com/rest-service/reviews-v1/filter/al" +
            "lClosedReviews?FEAUTH={0}")]
        public string ReviewsUrl {
            get {
                return ((string)(this["ReviewsUrl"]));
            }
            set {
                this["ReviewsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://fisheye.inside.nokiasiemensnetworks.com/rest-service/reviews-v1/{0}/comme" +
            "nts?FEAUTH={1}")]
        public string CommentUrl {
            get {
                return ((string)(this["CommentUrl"]));
            }
            set {
                this["CommentUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CrucibleUserName {
            get {
                return ((string)(this["CrucibleUserName"]));
            }
            set {
                this["CrucibleUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CruciblePassword {
            get {
                return ((string)(this["CruciblePassword"]));
            }
            set {
                this["CruciblePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RNCUP")]
        public string CrucibleProject {
            get {
                return ((string)(this["CrucibleProject"]));
            }
            set {
                this["CrucibleProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>accepted</string>
  <string>approved</string>
  <string>agree</string>
  <string>agree</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AcceptStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AcceptStrings"]));
            }
            set {
                this["AcceptStrings"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://docs.atlassian.com/fisheye-crucible/latest/wadl/crucible.html#d2e526")]
        public string CrucibleRESTAPIGuide {
            get {
                return ((string)(this["CrucibleRESTAPIGuide"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://jira.inside.nokiasiemensnetworks.com/rpc/soap/jirasoapservice-v2")]
        public string CrucibleData_com_nokiasiemensnetworks_inside_jira_JiraSoapServiceService {
            get {
                return ((string)(this["CrucibleData_com_nokiasiemensnetworks_inside_jira_JiraSoapServiceService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RNC")]
        public string JiraProjectName {
            get {
                return ((string)(this["JiraProjectName"]));
            }
            set {
                this["JiraProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://jira.inside.nokiasiemensnetworks.com/rpc/soap/jirasoapservice-v2")]
        public string JiraWebServiceBinding {
            get {
                return ((string)(this["JiraWebServiceBinding"]));
            }
            set {
                this["JiraWebServiceBinding"] = value;
            }
        }
    }
}
